mysql:
    datasource:
        test:
            jdbc-url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8&allowMultiQueries=true
            username: root
            password: red2028
            driver-class-name: com.mysql.cj.jdbc.Driver
        student:
            jdbc-url: jdbc:mysql://localhost:3306/student_management?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8&allowMultiQueries=true
            username: root
            password: red2028
            driver-class-name: com.mysql.cj.jdbc.Driver

scheduling:
    task:
        testTask:
            cron: 0 */1 * * * ?
        testHello:
            cron: 0 */1 * * * ?

redis:
    localhost:
        host: 0.0.0.0
        port: 6379
        database: 0
        password: ""
        timeout: 20000

neo4j:
    uri: bolt://localhost:7687
    username: neo4j
    password: zhangdong5211
